Content-type:text/html


<!DOCTYPE html>
<body>
<link rel="icon" href="data:,"> 
<center>
<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>TypeError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 3.8.10: /usr/bin/python<br>Mon Oct  3 20:58:37 2022</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///mnt/nfs/homes/threiss/ourWebserv/srcs/Server/www/cgi-bin/pythonGet.py">/mnt/nfs/homes/threiss/ourWebserv/srcs/Server/www/cgi-bin/pythonGet.py</a> in <strong>&lt;module&gt;</strong></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;16</small>&nbsp;print&nbsp;("&lt;link&nbsp;rel=\"icon\"&nbsp;href=\"data:,\"&gt;&nbsp;")<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;17</small>&nbsp;print&nbsp;("&lt;center&gt;")<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;18</small>&nbsp;print&nbsp;("&lt;h1&gt;Coucou&lt;/h1&gt;"&nbsp;+&nbsp;firstName)<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;19</small>&nbsp;print&nbsp;("&lt;center&gt;")<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;20</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><em>builtin</em> <strong>print</strong>&nbsp;= &lt;built-in function print&gt;, <strong>firstName</strong>&nbsp;= None</font></small></td></tr></table><p><strong>TypeError</strong>: can only concatenate str (not "NoneType") to str
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
('can only concatenate str (not "NoneType") to str',)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=
&lt;built-in method with_traceback of TypeError object&gt;


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "srcs/Server/www/cgi-bin/pythonGet.py", line 18, in &lt;module&gt;
    print ("&lt;h1&gt;Coucou&lt;/h1&gt;" + firstName)
TypeError: can only concatenate str (not "NoneType") to str

-->

